name: Build Docker container

on:
  push:
    branches:
      - 'master' 
  pull_request:
    branches: 
      - 'master'

env:
  REGISTRY_NAME: bcrshared.azurecr.io
  CLUSTER_NAME: qa-norwayeast-midgard-aks
  CLUSTER_RESOURCE_GROUP: qa-norwayeast-rg
  NAMESPACE: min-adresse

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Maven Package
        run: mvn clean package -DskipTests --file pom.xml

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Publish JAR
        run: mvn -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: homoluctus/gitrivy@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: bcrshared.azurecr.io/test:${{ github.sha }}
          ignore_unfixed: false
          issue_title: Trivy Security Alert from Dockerfile scan
          issue_label: trivy, vulnerability, dockerfile scan 
                      
            
